services:
  db:
    image: postgres:16-bookworm
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - django-web
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    env_file:
      - .env
volumes:
  postgres_data:
