name: Build and Push Docker Images

on:
  pull_request:
    branches:
      - main
    types: [labeled, opened, synchronize, reopened]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set Image Tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:${TAG} -f backend/Dockerfile backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${TAG}

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${TAG} -f frontend/Dockerfile frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${TAG}

      - name: Upload Artifact (env file)
        uses: actions/upload-artifact@v4
        with:
          name: docker-tag
          path: |
            docker_tag.txt
            run: echo "${TAG}" > docker_tag.txt
